name: Build for Windows
on: [push]
jobs: 
    Build-for-Windows:
        permissions:
          contents: write
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                 python-version: '3.12'
                 cache: 'pip'
            - run: pip install -r requirements.txt
            - run: pip install -U pyinstaller
            - run: .\build.bat
            - name: Archive artifacts
              uses: actions/upload-artifact@v4
              with:
                name: eoi
                path: |
                    dist/eoi
            - uses: ncipollo/release-action@v1
              with:
                artifacts: "eoi.zip"
                commit: ${{ github.sha }}
                tag: ${{ github.sha }}
